python python\visualize_pndf_mesh.py `
  --nxy-bin out256_4d_rebased\brush_ds4_nxy.bin `
  --meshbin out256_4d_rebased\brush_4d_ds4_v8192.meshbin `
  --out-dir vis_diag\brush_4d_v8192 `
  --crop auto `
  --crop-size 0.15 `
  --crop-pixels 2048 `
  --full-max-edges 0 `
  --diagnose-seam `
  --uv-shift 0.5,0.5 `
  --render-reconstruction `
  --error-heatmap