python python\visualize_pndf_mesh.py `
  --nxy-bin out_pnm_aniso\isotropic_ds4_nxy.bin `
  --meshbin out_debug\isotropic_pnm_aniso_he_flip_reloc_v16384.meshbin `
  --out-dir vis_aniso\isotropic_pnm_aniso_he_flip_reloc_v16384 `
  --crop 0.1,0.5,0.3 `
  --crop-size 0.15 `
  --crop-pixels 2048 `
  --full-max-edges 0 `
  --crop-max-edges 0 `
  --diagnose-seam `
  --uv-shift 0.5,0.5 `
  --render-reconstruction `
  --error-heatmap